### ISSUE TITLE
Encoding syllables error

### ISSUE THREAD

**Issue by esteng** [MontrealCorpusTools/speechcorpustools#32]
Encoding syllables gives the following error: 

Traceback (most recent call last):
  File "speechtools/workers.py", line 72, in run
  File "speechtools/workers.py", line 338, in run_query
  File "polyglotdb/corpus/syllabic.py", line 240, in encode_syllables
  File "polyglotdb/io/importer/from_csv.py", line 460, in import_nonsyl_csv
  File "polyglotdb/corpus/base.py", line 111, in execute_cypher
  File "py2neo/cypher/core.py", line 136, in execute
  File "py2neo/cypher/core.py", line 333, in commit
  File "py2neo/cypher/core.py", line 288, in post
  File "py2neo/cypher/error/core.py", line 54, in hydrate
AttributeError: module 'py2neo.cypher.error.statement' has no attribute 'ExecutionFailed'

**Comment by mmcauliffe** [comment]
So this looks like an issue that's being raised in an older version of py2neo than what we're using.  Since we've upgraded now to Neo4j 3.0, I'm going to close this, but it'd be good to rerun the manual testing suite with the latest version this week and see if we still get issues like this.
