### ISSUE TITLE
Encoding non-speech elements in Buckeye Error

### ISSUE THREAD

**Issue by esteng** [MontrealCorpusTools/speechcorpustools#33]
Encoding non-speech elements in Buckeye gave this error: 

Traceback (most recent call last):
  File "speechtools/workers.py", line 72, in run
  File "speechtools/workers.py", line 254, in run_query
  File "polyglotdb/corpus/pause.py", line 26, in encode_pauses
  File "polyglotdb/graph/query.py", line 739, in set_pause
  File "polyglotdb/graph/query.py", line 74, in set_pause
  File "polyglotdb/corpus/base.py", line 111, in execute_cypher
  File "py2neo/cypher/core.py", line 136, in execute
  File "py2neo/cypher/core.py", line 333, in commit
  File "py2neo/cypher/core.py", line 288, in post
  File "py2neo/cypher/error/core.py", line 54, in hydrate
AttributeError: module 'py2neo.cypher.error.statement' has no attribute 'ExecutionFailed'

**Comment by mmcauliffe** [comment]
See #32
