### ISSUE TITLE
Error related to resampling when selecting a discourse in binary

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/speechcorpustools#40]
In "something went wrong" window after trying to select a discourse in Buckeye (on OS X laptop):

Traceback (most recent call last):
  File "site-packages/resampy/filters.py", line 164, in get_filter
  File "site-packages/resampy/filters.py", line 193, in load_filter
  File "site-packages/numpy/lib/npyio.py", line 362, in load
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/SCT/sct.app/Contents/MacOS/resampy/data/kaiser_fast.npz'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "speechtools/workers.py", line 74, in run
  File "speechtools/workers.py", line 442, in run_query
  File "site-packages/polyglotdb/graph/discourse.py", line 46, in **init**
  File "site-packages/polyglotdb/graph/discourse.py", line 66, in refresh_cache
  File "site-packages/resampy/core.py", line 98, in resample
  File "site-packages/resampy/filters.py", line 167, in get_filter
NotImplementedError: Cannot load filter definition for kaiser_fast

**Comment by mmcauliffe** [comment]
Resampy needs to have its data files and libraries included when building using PyInstaller.

**Comment by mmcauliffe** [comment]
This is apparently Mac only, will need more investigation.
