### ISSUE TITLE
analyze acoustics for Timit failed

### ISSUE THREAD

**Issue by esteng** [MontrealCorpusTools/speechcorpustools#51]
Failed with this error message:

Traceback (most recent call last):
  File "speechtools/workers.py", line 75, in run
  File "speechtools/workers.py", line 210, in run_query
  File "site-packages/polyglotdb/acoustics/analysis.py", line 61, in acoustic_analysis
  File "site-packages/polyglotdb/acoustics/analysis.py", line 96, in analyze_pitch
  File "site-packages/acousticsim/main.py", line 371, in analyze_long_file
  File "site-packages/acousticsim/multiprocessing.py", line 182, in generate_cache_sig_dict
  File "multiprocessing/context.py", line 55, in Manager
  File "multiprocessing/managers.py", line 483, in start
  File "multiprocessing/connection.py", line 250, in recv
  File "multiprocessing/connection.py", line 407, in _recv_bytes
  File "multiprocessing/connection.py", line 383, in _recv
EOFError

**Comment by esteng** [comment]
Also failed with error for SOTC, and failed to encode formants or pitch for GlobalPhone and LibriSpeech. Only encoded pitch (no formants) for Buckeye

**Comment by esteng** [comment]
SOTC error:

Traceback (most recent call last):
  File "speechtools/workers.py", line 75, in run
  File "speechtools/workers.py", line 210, in run_query
  File "site-packages/polyglotdb/acoustics/analysis.py", line 61, in acoustic_analysis
  File "site-packages/polyglotdb/acoustics/analysis.py", line 96, in analyze_pitch
  File "site-packages/acousticsim/main.py", line 371, in analyze_long_file
  File "site-packages/acousticsim/multiprocessing.py", line 212, in generate_cache_sig_dict
acousticsim.exceptions.AcousticSimPythonError: Something went wrong that wasn't handled by acousticsim.
Please forward to the details below to the developers.
Traceback (most recent call last):
  File "site-packages/acousticsim/multiprocessing.py", line 109, in run
  File "site-packages/acousticsim/representations/reaper.py", line 41, in signal_to_pitch_reaper
  File "site-packages/acousticsim/representations/reaper.py", line 26, in file_to_pitch_reaper
  File "site-packages/acousticsim/representations/reaper.py", line 56, in parse_output
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/_l/9t4zdxl10h584njt5gqrkc3h0000gx/T/acousticsim7owpu6sr/tmpztlqinz_.f0'
