### ISSUE TITLE
No module named 'polyglotdb.graph'

### ISSUE THREAD

**Issue by alpoktem** [MontrealCorpusTools/speechcorpustools#61]
I was just running through the README.md to get the SCT running. I am stuck in step 4 running the debug script. Running on mac, Python 3.6 where polyglotdb (0.0.2) is installed. I get this error:

`Traceback (most recent call last):
  File "bin/qt_debug.py", line 5, in <module>
    from speechtools.main import MainWindow, QtWidgets
  File "/Users/alp/phdCloud/playground/speechcorpustools/speechtools/main.py", line 15, in <module>
    from .widgets import (ViewWidget, HelpWidget, DiscourseWidget, QueryWidget, CollapsibleWidgetPair,
  File "/Users/alp/phdCloud/playground/speechcorpustools/speechtools/widgets/__init__.py", line 4, in <module>
    from .connection import ConnectWidget
  File "/Users/alp/phdCloud/playground/speechcorpustools/speechtools/widgets/connection.py", line 12, in <module>
    from ..workers import AudioFinderWorker, AudioCheckerWorker
  File "/Users/alp/phdCloud/playground/speechcorpustools/speechtools/workers.py", line 10, in <module>
    from polyglotdb.graph.func import Sum
ModuleNotFoundError: No module named 'polyglotdb.graph'`

**Comment by mmcauliffe** [comment]
So at this point, the released polyglotdb has outpaced SCT in development, I would recommend using the released version of SCT to test out (https://github.com/MontrealCorpusTools/speechcorpustools/releases).  We're planning to have a stronger dev push for SCT that should incorporate the more recent polyglotdb this fall/winter.
